### ISSUE TITLE
How dare you make an add-on without telling me first!?

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [Chocohead/Tumble-Dryer#1]
If you had told me your plans in advance I would have set up things to make it easier for you!

Clothesline Fabric is now published on [https://maven.jamieswhiteshirt.com/libs-release/com/jamieswhiteshirt/clothesline-fabric/](https://maven.jamieswhiteshirt.com/libs-release/com/jamieswhiteshirt/clothesline-fabric/). The GitHub repository has been updated with instructions for how to use it with gradle.

Also a branding guideline: I much prefer "Clothesline" over "Clothes line".

**Comment by Chocohead** [comment]
Thanks for the maven, makes building the project much easier.

I've (tried to at least) use "Clothes line" when referring to real lines and "Clothesline" when referring to your mod. Feel free to point out anything that needs changing though.
